### ISSUE TITLE
Does it support "-rpc-header" params?

### ISSUE THREAD

**Issue by jiu-chen** [hudclark/grpc-nvim#3]

**Comment by hudclark** [comment]
Hi @jiu-chen.

Yes, this project supports passing headers in the following format: `grpc -rpc-header "foo: bar" localhost:50051 helloworld.Greeter/SayHello`

Note that the header value **must be quoted**. This project could be improved to better handle arguments with spaces, but for now, a workaround is to surround them in quotes.
